### ISSUE TITLE
Switch nav keys to standard WASD

### ISSUE THREAD

**Issue by samrushing** [stnbu/mass_gathering#5]
A feature request, really.  I feel like most people when faced with any kind of interactive game, their left hand instinctively moves to the standard WASD location.

**Comment by stnbu** [comment]
Probably needs a good configurator and a cookie (or something). Forgetting the cookie for now, probably not a big deal to get egui to display a little chooser configurator thing with checkboxes and number wheels.

So you could do the usual "pull up the game, head to the configuration menu..." and/or access it during play.

Complications:

1. Egui needs to display itself in both stereo. Probably not a big deal but requires some study on egui. It'd be kinda cool for all that to be like 10" in front of your face in 3d ...or whatever.
1. [There's](https://github.com/jakobhellermann/bevy-inspector-egui) a library/plugin that claims to let you control "any value" in word. If it can do that, it'd be easiest to find the components that let you map "egui widget" to "bevy Resource" without having to do it by hand. Hopefully handle "numbers" and "bool" and stuff automatically.

As far as mapping this stuff by hand, you could edit `src/craft.rs` and look for appearances of `KeyCode`.

A good middle-ground might be: take the key code stuff out and put it in its own "Plugin", then fork that so you have "MikeKeybindings" and "SamKeybindings" Plugins that you can compose in a "PluginBundle" as desired.

**Comment by stnbu** [comment]
There [was](https://github.com/stnbu/mass_gathering/blob/ee6d43fe2ee55ccda9e41923450471b999f25565/src/global_config.rs#L7) something like this. It got unwieldy because it doesn't introspect, everything's wired by hand.

**Comment by stnbu** [comment]
All [wrapped up](../commit/7dab0681668df8279814435d00911aa3d6d1ec40)? Nice job, Mike.
